name: Build and test jeteve_omniorb
on:
  push:  # Triggers on any push to any branch

jobs:
  build-test-omniorb:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - pyver: "3.14"
            pyabi: cp314
            omniorb_version: "4.3.3"
            docker_platform: linux/amd64
            manylinux_arch: x86_64
          - pyver: "3.14"
            pyabi: cp314
            omniorb_version: "4.3.2"
            docker_platform: linux/amd64
            manylinux_arch: x86_64
          - pyver: "3.13"
            pyabi: cp313
            omniorb_version: "4.3.3"
            docker_platform: linux/amd64
            manylinux_arch: x86_64
          - pyver: "3.13"
            pyabi: cp313
            omniorb_version: "4.3.2"
            docker_platform: linux/amd64
            manylinux_arch: x86_64
          - pyver: "3.12"
            pyabi: cp312
            omniorb_version: "4.3.3"
            docker_platform: linux/amd64
            manylinux_arch: x86_64
          - pyver: "3.12"
            pyabi: cp312
            omniorb_version: "4.3.2"
            docker_platform: linux/amd64
            manylinux_arch: x86_64
          - pyver: "3.11"
            pyabi: cp311
            omniorb_version: "4.3.3"
            docker_platform: linux/amd64
            manylinux_arch: x86_64
          - pyver: "3.11"
            pyabi: cp311
            omniorb_version: "4.3.2"
            docker_platform: linux/amd64
            manylinux_arch: x86_64
          - pyver: "3.10"
            pyabi: cp310
            omniorb_version: "4.3.3"
            docker_platform: linux/amd64
            manylinux_arch: x86_64
          - pyver: "3.10"
            pyabi: cp310
            omniorb_version: "4.3.2"
            docker_platform: linux/amd64
            manylinux_arch: x86_64
          - pyver: "3.10"
            pyabi: cp310
            omniorb_version: "4.2.6"
            docker_platform: linux/amd64
            manylinux_arch: x86_64
          - pyver: "3.9"
            pyabi: cp39
            omniorb_version: "4.2.6"
            docker_platform: linux/amd64
            manylinux_arch: x86_64
          - pyver: "3.8"
            pyabi: cp38
            omniorb_version: "4.2.6"
            docker_platform: linux/amd64
            manylinux_arch: x86_64


            
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures all tags and history are available
    
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3  
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker builder image
        run: |
          docker build \
            --platform ${{ matrix.docker_platform }} \
            --build-arg MANYLINUX_ARCH=${{ matrix.manylinux_arch }} \
            --tag my-builder:${{ github.sha }} \
            . \

      - name: Get user info
        id: user-info
        run: |
          echo "uid=$(id -u)" >> $GITHUB_OUTPUT
          echo "gid=$(id -g)" >> $GITHUB_OUTPUT
        
      - name: Test docker image
        uses: addnab/docker-run-action@v3
        with:
          image: my-builder:${{ github.sha }}
          options: --platform ${{ matrix.docker_platform }} --user ${{ steps.user-info.outputs.uid }}:${{ steps.user-info.outputs.gid }} -v ${{ github.workspace }}:/workdir
          run: |
            echo "Running as UID: $(id -u), GID: $(id -g)"
            echo "Success!"

      - name: "Build wheel"
        uses: addnab/docker-run-action@v3
        with:
          image: my-builder:${{ github.sha }}
          options: --platform ${{ matrix.docker_platform }} --user ${{ steps.user-info.outputs.uid }}:${{ steps.user-info.outputs.gid }} -t -v ${{ github.workspace }}:/workdir -e HOME=/workdir
          run: bash /workdir/inside-build-wheels.sh ${{ matrix.pyabi }} ${{ matrix.omniorb_version }}

      - name: Test wheel
        uses: addnab/docker-run-action@v3
        with:
          image: my-builder:${{ github.sha }}
          options: --platform ${{ matrix.docker_platform }} --user ${{ steps.user-info.outputs.uid }}:${{ steps.user-info.outputs.gid }} -v ${{ github.workspace }}:/workdir -e HOME=/workdir
          run: bash /workdir/inside-test-wheels.sh ${{ matrix.pyver }} ${{ matrix.omniorb_version }}

      - name: Save wheel as artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheel-${{ matrix.omniorb_version }}-${{ matrix.pyver }}-${{ matrix.manylinux_arch }}
          path: wheelhouse/
  
  gather-wheels:
    needs: build-test-omniorb
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: wheel-*
          path: wheelhouse/
          merge-multiple: true

      - name: List wheels
        run: |
          ls -l wheelhouse/

      - name: Save all wheels as artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheelhouse
          path: wheelhouse/


